[package]
name = "cpython-gen"
version = "0.1.0"
authors = ["Flier Lu <flier.lu@gmail.com>"]

[dependencies]
log = "0.3"
error-chain = "0.9"
regex = "0.2"
syn = "0.11"
syntex_syntax = "0.58"
syntex_errors = "0.58"
quote = "0.3"
rustfmt = "0.7"
cargo = "0.16"

[dependencies.aster]
version = "0.41"
features = ["with-syntex"]
